[package]
name = "armagram"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
log = "0.4.17"
regex = "1.6.0"
reqwest = { version = "0.11.11", features = ["blocking"] }
systemd-journal-logger = "0.5.0"
